services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gestionare_angajati
      MYSQL_USER: userapp
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: ./GestionareAngajatiAPI
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "5000:8080"
    depends_on:
      - mysql-db

  frontend:
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://api:8080
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  mysql_data:
